Bringup system-squisher for Nougat (2/2)
Other commit is in build
Based on Cl3kener and FusionJacks Lollipop commits

# Conflicts:
#	config/common.mk
#	tools/colors
#	tools/squisher

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -8,23 +8,23 @@
 OUT_TARGET_HOST=`uname -s`
 if [ x"$OUT_TARGET_HOST" = x"Linux" ]
 then
-    OUT_TARGET_HOST=linux-x86
-    XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
+   OUT_TARGET_HOST=linux-x86
+   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
 elif [ x"$OUT_TARGET_HOST" = x"Darwin" ]
 then
-    OUT_TARGET_HOST=darwin-x86
-    XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
+   OUT_TARGET_HOST=darwin-x86
+   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
 else
-    echo -e "${bldred}ERROR: unknown/unsupported host OS!${rst}"
-    exit 1
+   echo -e ${CL_RED}"ERROR: unknown/unsupported host OS!"${CL_RST}
+   exit 1
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo -e "${bldred}ERROR: $0 only works with a full build environment. $OUT should exist.${rst}"
-    exit 1
+	echo -e ${CL_RED}"ERROR: $0 only works with a full build environment. $OUT should exist."${CL_RST}
+	exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/vendor/cmremix/tools/opticharger
+CRUSHER=$ANDROID_BUILD_TOP/vendor/cmremix/tools/crusher
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
@@ -55,6 +55,6 @@ if [ "$CMREMIX_LOW_RAM_DEVICE" = "true" ]; then
 fi
 
 # Optimize PNG resources in APKs
-( cd $OUT/system; find framework/ app/ priv-app/ ! -name 'webview.apk' -name \*.apk -print | $XARGS $OPTICHARGER; )
+( cd $OUT/system; find framework/ app/ priv-app/ -name \*.apk -print | $XARGS $CRUSHER; )
 
 exit 0
